### PR TITLE
Add support for ignoring IRC hosts from Discord

### PR DESCRIPTION
**Pull request by llmII**
This should add a configuration option that allows for using nearly IRC style hostmasks to "ban" matching users in IRC from sending messages towards Discord. This would be useful for ignoring bots in channels.

Submitting this as a draft because there might be something else that would be wanted but am not sure if it's worth the effort or the tradeoff.

Should we cache matches (as in, if a nick matches once, cache it until config reload)? The tradeoff is memory for speed. I'm not certain this will have a speed issue until ignoring probably thousands of hosts from IRC.

~~Will add the appropriate documentation and such after having actually tested that this works as believed it should.~~

Tested, works, documentation and configuration example added.

### CODE REVIEW

**Comment by llmII** [comment]
Note: PR #72  will need another branch to add a feature that supports ignoring IRC users like this PR does for JOIN/QUIT/PART and messages.

**Comment by llmII** [comment]
Tested now and added documentation. Should be ready for checking.

**Review by qaisjp — APPROVED** [review]
Thank you!

**Comment by qaisjp** [comment]
And yeah I agree with your judgement call — it's probably fine matching every time. It would be useful to add live reload here in the future, it seems like it wouldn't be too hard to implement!

**Comment by llmII** [comment]
> And yeah I agree with your judgement call — it's probably fine matching every time. It would be useful to add live reload here in the future, it seems like it wouldn't be too hard to implement!

Live reload? as in if the config changes and irc_ignored_hostmasks are changed it stops/starts ignoring added/removed hostmasks? If so that's already done but if not let me know what you meant by live reload and I'll likely add it to my list of things to get after.

**Comment by qaisjp** [comment]
Ah, okay, awesome :)

I keep mixing up the "requires restart" column with "supports live reload" haha

**Pull request merged**
