### PR TITLE
Feature: Ignore messages containing matching text

### PR DESCRIPTION
**Pull request by llmII**
This feature allows for when a message matches from Discord towards IRC
or the other way around for the matching message to be dropped
(filtered).

Will test in a bit, uses the same globber used for IRC Hostmasks.

**EDIT:**
Tested, works.

### CODE REVIEW

**Review by qaisjp — APPROVED** [review]
I'm a little bit hesitant about adding features for every little bit of customisation (where maintaining a fork would be easier), but the end-state of this project is to be merged into matterbridge, so I'm happy with just approving and merging this now.

When we eventually get this project incorporated into matterbridge, this feature likely will be made redundant with matterbridge's scripting interface — tengo.

**Comment by qaisjp** [comment]
There is a merge conflict, please resolve at your leisure :)

**Comment by llmII** [comment]
> I'm a little bit hesitant about adding features for every little bit of customisation (where maintaining a fork would be easier), but the end-state of this project is to be merged into matterbridge, so I'm happy with just approving and merging this now.

Understand and makes sense. I should have included a rationale for this change. Basically lets say there is an urban dictionary bot on xyz side of the bridge. Now it also does other useful things, but we know that urban dictionary can be floody for say "the longest definition on urbandictionary" query. Luck has it that whoever made the bot decided each line of urban dictionary related output should be prefixed "[ud]" so we can filter on this and keep the remainder of useful things. It also conveniently works for ignoring users that are behind a relay when a channel runs multiple kinds of relays (should be less of an issue when matterbridge is used since it bridges *everything* tho :D
 
> When we eventually get this project incorporated into matterbridge, this feature likely will be made redundant with matterbridge's scripting interface — tengo.

A scripting interface would be pretty dang cool!





> There is a merge conflict, please resolve at your leisure :)

Will work on this in just a moment...

**Comment by llmII** [comment]
Merge conflict resolved.

**Comment by qaisjp** [comment]
Thank you :)

**Pull request merged**
